### ISSUE TITLE
This typeface is restricted to Apple.

### ISSUE THREAD

**Issue by ivan-avalos** [ZulwiyozaPutra/SF-Mono-Font#3]
Unlike SF Pro typeface, which is restricted to iOS, macOS and tvOS developers, SF Mono is restricted only for use in Apple developer tools. That's why it's embedded inside Xcode and Terminal instead of being a system font. You can't even download it from the website, only SF Pro and New York are available.

Sorry dude, I'm sorry to tell you that you will have to delete this repository because of the SF Mono extra-restrictive licence.

**Comment by rindeal** [comment]
It's available on Apple's website as of now

![Screenshot_20190904_100609](https://user-images.githubusercontent.com/5360877/64236902-dacc4500-ceea-11e9-9b10-e40b6447f7f7.png)

**Comment by ivan-avalos** [comment]
Wow, I swear it was not there when I submitted this issue. Originally, you had to extract it from apps bundled with it. Check the license just in case.

**Comment by dtinth** [comment]
Here’s the license from the font file downloaded from Apple’s website, for reference:

> This SF Mono Font (the “Apple Font”) is licensed to you by Apple Inc. (“Apple”) in consideration of your agreement to the following terms and the terms of the License Agreement for the Apple SF Mono Font that was presented upon the downloading of the Apple Font. If you do not agree with these terms and the terms of the License Agreement for the Apple SF Mono Font, do not use the Apple Font.  
>
> You may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS, iPadOS, macOS or tvOS operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS, iPadOS, macOS or tvOS.
>
> The grants set forth in this License do not permit you to, and you agree not to, install, use or run the Apple Font for the purpose of creating mock-ups of user interfaces to be used in software products running on any non-Apple operating system or to enable others to do so. You may not embed the Apple Font in any software programs or other products. Except as expressly provided for herein, you may not use the Apple Font to, create, develop, display or otherwise distribute any documentation, artwork, website content or any other work product.
>
> You may use the Apple Font: (i) only for the purposes described in this License and the License Agreement for the Apple SF Mono Font; and (ii) only if you are a Registered Apple Developer, or as otherwise expressly permitted by Apple in writing.
